# Generated by Django 3.0 on 2019-12-11 02:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('createdBy', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-createdAt'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('postTitle', models.CharField(max_length=50)),
                ('postDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ['-createdAt'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('repliedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.CharField(max_length=500)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Comment')),
            ],
            options={
                'ordering': ['-createdAt'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Post'),
        ),
    ]
