# Generated by Django 3.0 on 2020-01-25 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('firstLastName', models.CharField(max_length=50)),
                ('secondLastName', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('createdBy', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-createdAt'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('postTitle', models.CharField(max_length=50)),
                ('postDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ['-createdAt'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('cost', models.FloatField()),
                ('percentage', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('repliedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.CharField(max_length=500)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Comment')),
            ],
            options={
                'ordering': ['-createdAt'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('date', models.DateField()),
                ('total', models.FloatField()),
                ('amountPaid', models.FloatField()),
                ('totalRemaining', models.FloatField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Service')),
            ],
            options={
                'ordering': ['-createdAt'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Post'),
        ),
    ]
